#!/usr/bin/env python3
"""Contract drift gate: regenerate from spec and byte-compare against the mirrors.

Nested repos are independent git checkouts, so this compares generated bytes to
the on-disk mirrors directly (no parent `git diff`). Non-zero exit == drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main(["--check"]))
