#!/usr/bin/env node

import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, relative, resolve } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath, pathToFileURL } from "node:url";

const execFileAsync = promisify(execFile);
const contractRoot = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(contractRoot, "..");
const defaultMirrors = [
  resolve(repositoryRoot, "kokoro-platform/kokoro-platform-admin/src/generated/contracts"),
  resolve(repositoryRoot, "kokoro-web/apps/admin/lib/generated/contracts"),
];

function parseArguments(argv) {
  if (argv.length === 0) return { output: null };
  if (argv.length !== 2 || argv[0] !== "--output" || argv[1].length === 0) {
    throw new Error("contract_generation_arguments_invalid");
  }
  return { output: resolve(argv[1]) };
}

async function protoFiles(directory, current = directory) {
  const entries = await readdir(current, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const path = resolve(current, entry.name);
    if (entry.isDirectory()) files.push(...(await protoFiles(directory, path)));
    else if (entry.isFile() && entry.name.endsWith(".proto")) files.push(path);
  }
  return files;
}

async function artifactFiles(directory, current = directory) {
  const entries = await readdir(current, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const path = resolve(current, entry.name);
    if (entry.isDirectory()) files.push(...(await artifactFiles(directory, path)));
    else if (entry.isFile() && entry.name !== "contract-metadata.ts") files.push(path);
  }
  return files;
}

async function sourceMetadata() {
  const protoRoot = resolve(contractRoot, "proto");
  const files = await protoFiles(protoRoot);
  const hash = createHash("sha256");
  const sourcePaths = [];
  for (const path of files) {
    const sourcePath = relative(protoRoot, path).replaceAll("\\", "/");
    sourcePaths.push(sourcePath);
    hash.update(`${sourcePath}\0`);
    hash.update(await readFile(path));
    hash.update("\0");
  }
  const packageJson = JSON.parse(await readFile(resolve(contractRoot, "package.json"), "utf8"));
  return {
    schemaId: "kokoro.platform.admin.v1.AdminAuthService",
    schemaVersion: 1,
    sourceDigestSha256: hash.digest("hex"),
    sourcePaths,
    generatorVersion: packageJson.devDependencies["@bufbuild/protoc-gen-es"],
    runtimeVersion: packageJson.devDependencies["@bufbuild/protobuf"],
  };
}

async function contractMetadata(mirror = defaultMirrors[0]) {
  const metadata = await sourceMetadata();
  const hash = createHash("sha256");
  for (const path of await artifactFiles(mirror)) {
    const artifactPath = relative(mirror, path).replaceAll("\\", "/");
    hash.update(`${artifactPath}\0`);
    hash.update(await readFile(path));
    hash.update("\0");
  }
  return { ...metadata, artifactDigestSha256: hash.digest("hex") };
}

function metadataSource(metadata) {
  const paths = metadata.sourcePaths.map((path) => `    ${JSON.stringify(path)},`).join("\n");
  return `// @generated by contract/generate.mjs; DO NOT EDIT.\n` +
    `export const contractMetadata = Object.freeze({\n` +
    `  schemaId: ${JSON.stringify(metadata.schemaId)},\n` +
    `  schemaVersion: ${metadata.schemaVersion},\n` +
    `  sourceDigestSha256: ${JSON.stringify(metadata.sourceDigestSha256)},\n` +
    `  artifactDigestSha256: ${JSON.stringify(metadata.artifactDigestSha256)},\n` +
    `  sourcePaths: Object.freeze([\n${paths}\n  ]),\n` +
    `  generatorVersion: ${JSON.stringify(metadata.generatorVersion)},\n` +
    `  runtimeVersion: ${JSON.stringify(metadata.runtimeVersion)},\n` +
    `});\n`;
}

function adminAuthEffectDigestSource() {
  return `// @generated by contract/generate.mjs; DO NOT EDIT.\n` +
    `import { createHash } from "node:crypto";\n` +
    `import { create, toBinary } from "@bufbuild/protobuf";\n` +
    `import { CommandDigestAlgorithm } from "./kokoro/common/v1/receipt_pb.js";\n` +
    `import {\n` +
    `  ConsumeVerificationTokenEffectSchema,\n` +
    `  CreateVerificationTokenEffectSchema,\n` +
    `  RecordAuthEventEffectSchema,\n` +
    `  type ConsumeVerificationTokenEffect,\n` +
    `  type CreateVerificationTokenEffect,\n` +
    `  type RecordAuthEventEffect,\n` +
    `} from "./kokoro/platform/admin/v1/admin_auth_pb.js";\n\n` +
    `export const ADMIN_AUTH_COMMAND_DIGEST_ALGORITHM =\n` +
    `  CommandDigestAlgorithm.SHA256_PROTOBUF_V1;\n\n` +
    `function normalizeEmail(value: string): string {\n` +
    `  return value.trim().toLowerCase();\n` +
    `}\n\n` +
    `function digest(typeName: string, bytes: Uint8Array): string {\n` +
    `  const hash = createHash("sha256");\n` +
    `  hash.update(typeName, "utf8");\n` +
    `  hash.update(Uint8Array.of(0));\n` +
    `  hash.update(bytes);\n` +
    `  return hash.digest("hex");\n` +
    `}\n\n` +
    `export function canonicalizeCreateVerificationTokenEffect(\n` +
    `  effect: CreateVerificationTokenEffect,\n` +
    `): CreateVerificationTokenEffect {\n` +
    `  return create(CreateVerificationTokenEffectSchema, {\n` +
    `    identifier: normalizeEmail(effect.identifier),\n` +
    `    token: effect.token,\n` +
    `    ...(effect.expires === undefined ? {} : { expires: effect.expires }),\n` +
    `  });\n` +
    `}\n\n` +
    `export function createVerificationTokenEffectDigest(effect: CreateVerificationTokenEffect): string {\n` +
    `  const canonical = canonicalizeCreateVerificationTokenEffect(effect);\n` +
    `  return digest(\n` +
    `    CreateVerificationTokenEffectSchema.typeName,\n` +
    `    toBinary(CreateVerificationTokenEffectSchema, canonical, { writeUnknownFields: false }),\n` +
    `  );\n` +
    `}\n\n` +
    `export function canonicalizeConsumeVerificationTokenEffect(\n` +
    `  effect: ConsumeVerificationTokenEffect,\n` +
    `): ConsumeVerificationTokenEffect {\n` +
    `  return create(ConsumeVerificationTokenEffectSchema, {\n` +
    `    identifier: normalizeEmail(effect.identifier),\n` +
    `    token: effect.token,\n` +
    `  });\n` +
    `}\n\n` +
    `export function consumeVerificationTokenEffectDigest(effect: ConsumeVerificationTokenEffect): string {\n` +
    `  const canonical = canonicalizeConsumeVerificationTokenEffect(effect);\n` +
    `  return digest(\n` +
    `    ConsumeVerificationTokenEffectSchema.typeName,\n` +
    `    toBinary(ConsumeVerificationTokenEffectSchema, canonical, { writeUnknownFields: false }),\n` +
    `  );\n` +
    `}\n\n` +
    `export function canonicalizeRecordAuthEventEffect(effect: RecordAuthEventEffect): RecordAuthEventEffect {\n` +
    `  const reason = effect.reason === undefined || effect.reason.length === 0 ? undefined : effect.reason;\n` +
    `  return create(RecordAuthEventEffectSchema, {\n` +
    `    email: normalizeEmail(effect.email),\n` +
    `    event: effect.event,\n` +
    `    ...(reason === undefined ? {} : { reason }),\n` +
    `    ...(effect.occurredAt === undefined ? {} : { occurredAt: effect.occurredAt }),\n` +
    `  });\n` +
    `}\n\n` +
    `export function recordAuthEventEffectDigest(effect: RecordAuthEventEffect): string {\n` +
    `  const canonical = canonicalizeRecordAuthEventEffect(effect);\n` +
    `  return digest(\n` +
    `    RecordAuthEventEffectSchema.typeName,\n` +
    `    toBinary(RecordAuthEventEffectSchema, canonical, { writeUnknownFields: false }),\n` +
    `  );\n` +
    `}\n`;
}

function singleOutputTemplate(output) {
  return `version: v2\nclean: true\nplugins:\n  - local: protoc-gen-es\n    out: ${JSON.stringify(output)}\n    include_imports: true\n    opt:\n      - target=ts\n      - import_extension=js\n`;
}

async function runBufGenerate(output) {
  const command = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
  if (output === null) {
    await execFileAsync(command, ["exec", "buf", "generate"], {
      cwd: contractRoot,
      timeout: 120_000,
      maxBuffer: 1024 * 1024,
    });
    return defaultMirrors;
  }

  const temporary = await mkdtemp(resolve(tmpdir(), "kokoro-buf-template-"));
  const template = resolve(temporary, "buf.gen.yaml");
  try {
    await writeFile(template, singleOutputTemplate(output), "utf8");
    await execFileAsync(command, ["exec", "buf", "generate", "--template", template], {
      cwd: contractRoot,
      timeout: 120_000,
      maxBuffer: 1024 * 1024,
    });
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
  return [output];
}

async function generate(options) {
  const mirrors = await runBufGenerate(options.output);
  const digestSource = adminAuthEffectDigestSource();
  await Promise.all(
    mirrors.map((mirror) => writeFile(resolve(mirror, "admin-auth-effect-digest.ts"), digestSource, "utf8")),
  );
  const metadata = await Promise.all(mirrors.map((mirror) => contractMetadata(mirror)));
  if (metadata.some(({ artifactDigestSha256 }) => artifactDigestSha256 !== metadata[0].artifactDigestSha256)) {
    throw new Error("contract_generation_artifact_mismatch");
  }
  const source = metadataSource(metadata[0]);
  await Promise.all(mirrors.map((mirror) => writeFile(resolve(mirror, "contract-metadata.ts"), source, "utf8")));
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  try {
    await generate(parseArguments(process.argv.slice(2)));
  } catch {
    process.stderr.write("contract_generation_failed\n");
    process.exitCode = 1;
  }
}

export { adminAuthEffectDigestSource, contractMetadata, generate, metadataSource, parseArguments };
